### PR TITLE
Issue 2

### PR DESCRIPTION
**Pull request by pfmluis**
[Issue 2](https://github.com/estg-masters-pedwm/SmartHome/issues/2)

### CODE REVIEW

**Comment by pfmluis** [comment]
This issue took some more time to be implemented because of integration issues with other components of Firebase

**Comment by pfmluis** [comment]
I tested it with briefly, but I'd like you to check other components you've implemented before

**Comment by RicardooCorreia** [comment]
Was this tested?

**Comment by pfmluis** [comment]
Yes, it was. It was tested, after the integration of the FCM and the creation of the receiving message handler. A notification  was fired from the Firebase Console and it was received correctly by the handler. Although I'd like you to run through the main activities and see if this version from the FCM didn't break any other Firebase functionalities (since you have a bigger knowledge of what's implemented, and its expected behaviours).

**Review by RicardooCorreia — APPROVED** [review]

**Pull request merged**
